#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;

extern void _Alpha_CaL_reg(void);
extern void _Alpha_CaPQ_reg(void);
extern void _Alpha_CaT_reg(void);
extern void _Alpha_GIRK_reg(void);
extern void _Alpha_Glucagon_reg(void);
extern void _Alpha_Ka_reg(void);
extern void _Alpha_KATP_reg(void);
extern void _Alpha_KDR_reg(void);
extern void _Alpha_L_reg(void);
extern void _Alpha_Na_reg(void);
extern void _Beta_BK_reg(void);
extern void _Beta_Cac_reg(void);
extern void _Beta_CaL_reg(void);
extern void _Beta_CaP_reg(void);
extern void _Beta_CaT_reg(void);
extern void _Beta_HERG_reg(void);
extern void _Beta_Ins_reg(void);
extern void _Beta_Insulin_reg(void);
extern void _Beta_KATP_reg(void);
extern void _Beta_KCa_reg(void);
extern void _Beta_KDR_reg(void);
extern void _Beta_NaB_reg(void);
extern void _Beta_Na_reg(void);
extern void _Beta_PCa_reg(void);
extern void _Beta_V_reg(void);
extern void _Delta_CaL_reg(void);
extern void _Delta_CaPQ_reg(void);
extern void _Delta_GABA_reg(void);
extern void _Delta_Ka_reg(void);
extern void _Delta_KATP_reg(void);
extern void _Delta_Kdr_reg(void);
extern void _Delta_L_reg(void);
extern void _Delta_Na_reg(void);
extern void _Delta_Somatostatin_reg(void);

void modl_reg(){
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");

    fprintf(stderr," Alpha_CaL.mod");
    fprintf(stderr," Alpha_CaPQ.mod");
    fprintf(stderr," Alpha_CaT.mod");
    fprintf(stderr," Alpha_GIRK.mod");
    fprintf(stderr," Alpha_Glucagon.mod");
    fprintf(stderr," Alpha_Ka.mod");
    fprintf(stderr," Alpha_KATP.mod");
    fprintf(stderr," Alpha_KDR.mod");
    fprintf(stderr," Alpha_L.mod");
    fprintf(stderr," Alpha_Na.mod");
    fprintf(stderr," Beta_BK.mod");
    fprintf(stderr," Beta_Cac.mod");
    fprintf(stderr," Beta_CaL.mod");
    fprintf(stderr," Beta_CaP.mod");
    fprintf(stderr," Beta_CaT.mod");
    fprintf(stderr," Beta_HERG.mod");
    fprintf(stderr," Beta_Ins.mod");
    fprintf(stderr," Beta_Insulin.mod");
    fprintf(stderr," Beta_KATP.mod");
    fprintf(stderr," Beta_KCa.mod");
    fprintf(stderr," Beta_KDR.mod");
    fprintf(stderr," Beta_NaB.mod");
    fprintf(stderr," Beta_Na.mod");
    fprintf(stderr," Beta_PCa.mod");
    fprintf(stderr," Beta_V.mod");
    fprintf(stderr," Delta_CaL.mod");
    fprintf(stderr," Delta_CaPQ.mod");
    fprintf(stderr," Delta_GABA.mod");
    fprintf(stderr," Delta_Ka.mod");
    fprintf(stderr," Delta_KATP.mod");
    fprintf(stderr," Delta_Kdr.mod");
    fprintf(stderr," Delta_L.mod");
    fprintf(stderr," Delta_Na.mod");
    fprintf(stderr," Delta_Somatostatin.mod");
    fprintf(stderr, "\n");
  }
  _Alpha_CaL_reg();
  _Alpha_CaPQ_reg();
  _Alpha_CaT_reg();
  _Alpha_GIRK_reg();
  _Alpha_Glucagon_reg();
  _Alpha_Ka_reg();
  _Alpha_KATP_reg();
  _Alpha_KDR_reg();
  _Alpha_L_reg();
  _Alpha_Na_reg();
  _Beta_BK_reg();
  _Beta_Cac_reg();
  _Beta_CaL_reg();
  _Beta_CaP_reg();
  _Beta_CaT_reg();
  _Beta_HERG_reg();
  _Beta_Ins_reg();
  _Beta_Insulin_reg();
  _Beta_KATP_reg();
  _Beta_KCa_reg();
  _Beta_KDR_reg();
  _Beta_NaB_reg();
  _Beta_Na_reg();
  _Beta_PCa_reg();
  _Beta_V_reg();
  _Delta_CaL_reg();
  _Delta_CaPQ_reg();
  _Delta_GABA_reg();
  _Delta_Ka_reg();
  _Delta_KATP_reg();
  _Delta_Kdr_reg();
  _Delta_L_reg();
  _Delta_Na_reg();
  _Delta_Somatostatin_reg();
}
