#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/apps/neuron/7.7.2"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/apps/neuron/7.7.2/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/tikaharikhanal/lamb_tikaharikhanal/Model-of-Pancreatic-Islets/Test/x86_64/.libs/libnrnmech.so" "$@"
